name: TDA
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _tflow_select=2.3.0=mkl
  - absl-py=0.9.0=py38h32f6830_1
  - astunparse=1.6.3=py_0
  - backcall=0.1.0=py38_0
  - blas=1.0=openblas
  - blinker=1.4=py_1
  - boost-cpp=1.70.0=ha2d47e9_1
  - brotlipy=0.7.0=py38h1e0a361_1000
  - bzip2=1.0.8=h516909a_2
  - c-ares=1.15.0=h516909a_1001
  - ca-certificates=2020.1.1=0
  - cachetools=4.1.0=py_1
  - certifi=2020.4.5.2=py38_0
  - cffi=1.14.0=py38he30daa8_1
  - cgal-cpp=5.0.1=h261e690_0
  - chardet=3.0.4=py38h32f6830_1006
  - click=7.1.2=pyh9f0ad1d_0
  - cryptography=2.9.2=py38h766eaa4_0
  - cycler=0.10.0=py_2
  - dbus=1.13.14=hb2f20db_0
  - decorator=4.4.2=py_0
  - eigen=3.3.7=hc9558a2_1001
  - entrypoints=0.3=py38_0
  - expat=2.2.9=he1b5a44_2
  - fontconfig=2.13.1=he4413a7_1000
  - freetype=2.10.2=he06d7ca_0
  - gast=0.3.3=py_0
  - glib=2.63.1=h3eb4bd4_1
  - gmp=6.2.0=he1b5a44_2
  - google-auth=1.17.2=py_0
  - google-auth-oauthlib=0.4.1=py_2
  - google-pasta=0.2.0=pyh8c360ce_0
  - grpcio=1.27.2=py38hf8bcb03_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb31296c_0
  - gudhi=3.1.1=py38hb3f55d8_0
  - h5py=2.10.0=nompi_py38h513d04c_102
  - hdf5=1.10.5=nompi_h3c11f04_1104
  - icu=58.2=hf484d3e_1000
  - idna=2.9=py_1
  - importlib-metadata=1.6.1=py38h32f6830_0
  - ipykernel=5.1.4=py38h39e3cac_0
  - ipython=7.13.0=py38h5ca1d4c_0
  - ipython_genutils=0.2.0=py38_0
  - jedi=0.17.0=py38_0
  - joblib=0.15.1=py_0
  - jpeg=9d=h516909a_0
  - jupyter_client=6.1.3=py_0
  - jupyter_core=4.6.3=py38_0
  - keras=2.3.1=0
  - keras-applications=1.0.8=py_1
  - keras-base=2.3.1=py38_0
  - keras-preprocessing=1.1.0=py_0
  - kiwisolver=1.2.0=py38hbf85e49_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libblas=3.8.0=14_openblas
  - libcblas=3.8.0=14_openblas
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.3=he6710b0_1
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.5.0=hdf63c60_6
  - libiconv=1.15=h516909a_1006
  - liblapack=3.8.0=14_openblas
  - libopenblas=0.3.7=h5ec1e0e_6
  - libpng=1.6.37=hed695b0_1
  - libprotobuf=3.12.3=h8b12597_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libuuid=2.32.1=h14c3975_1000
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.9=h13577e0_2
  - lz4-c=1.9.2=he1b5a44_1
  - markdown=3.2.2=py_0
  - matplotlib=3.1.3=py38_0
  - matplotlib-base=3.1.3=py38hef1b27d_0
  - mpfr=4.0.2=he80fd80_1
  - ncurses=6.2=he6710b0_1
  - nose=1.3.7=py38h32f6830_1004
  - numpy=1.18.5=py38h8854b6b_0
  - oauthlib=3.0.1=py_0
  - openssl=1.1.1g=h7b6447c_0
  - opt_einsum=3.2.1=py_0
  - pandas=1.0.3=py38h0573a6f_0
  - parso=0.7.0=py_0
  - pcre=8.44=he1b5a44_0
  - pexpect=4.8.0=py38_0
  - pickleshare=0.7.5=py38_1000
  - pip=20.0.2=py38_3
  - prompt-toolkit=3.0.5=py_0
  - prompt_toolkit=3.0.5=0
  - protobuf=3.12.3=py38h950e882_0
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py38_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.20=py_0
  - pygments=2.6.1=py_0
  - pyjwt=1.7.1=py_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.9.2=py38h05f1152_4
  - pysocks=1.7.1=py38h32f6830_1
  - python=3.8.3=hcff3b4d_0
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytz=2020.1=py_0
  - pyyaml=5.3.1=py38h1e0a361_0
  - pyzmq=18.1.1=py38he6710b0_0
  - qt=5.9.7=h5867ecd_1
  - readline=8.0=h7b6447c_0
  - requests=2.23.0=pyh8c360ce_2
  - requests-oauthlib=1.2.0=py_0
  - rsa=4.6=pyh9f0ad1d_0
  - scikit-learn=0.22.1=py38h22eb022_0
  - scikit-plot=0.3.7=py_1
  - scipy=1.4.1=py38h18bccfc_3
  - setuptools=47.1.1=py38_0
  - sip=4.19.13=py38he6710b0_0
  - six=1.15.0=pyh9f0ad1d_0
  - sqlite=3.31.1=h62c20be_1
  - tensorboard=2.2.1=pyh532a8cf_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - tensorflow=2.2.0=mkl_py38h6d3daf0_0
  - tensorflow-base=2.2.0=mkl_py38h5059a2d_0
  - tensorflow-estimator=2.2.0=pyh208ff02_0
  - termcolor=1.1.0=py_2
  - tk=8.6.8=hbc83047_0
  - tornado=6.0.4=py38h1e0a361_1
  - traitlets=4.3.3=py38_0
  - urllib3=1.25.9=py_0
  - wcwidth=0.1.9=py_0
  - werkzeug=1.0.1=pyh9f0ad1d_0
  - wfdb=2.2.1=py_1
  - wheel=0.34.2=py38_0
  - wrapt=1.12.1=py38h1e0a361_1
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h516909a_0
  - zeromq=4.3.1=he6710b0_3
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.4=h6597ccf_3
prefix: /home/antic/anaconda3/envs/TDA

