name: tda
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py_0
  - bleach=3.1.5=pyh9f0ad1d_0
  - boost-cpp=1.72.0=h8e57a91_0
  - brotlipy=0.7.0=py38h1e0a361_1000
  - bzip2=1.0.8=h516909a_2
  - ca-certificates=2020.4.5.1=hecc5488_0
  - certifi=2020.4.5.1=py38h32f6830_0
  - cffi=1.14.0=py38hd463f26_0
  - cgal-cpp=5.0.1=h747953b_1
  - chardet=3.0.4=py38h32f6830_1006
  - cryptography=2.9.2=py38h766eaa4_0
  - cycler=0.10.0=py_2
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - eigen=3.3.7=hc9558a2_1001
  - entrypoints=0.3=py38h32f6830_1001
  - expat=2.2.6=he6710b0_0
  - freetype=2.10.2=he06d7ca_0
  - git=2.23.0=pl526hacde149_0
  - gmp=6.2.0=he1b5a44_2
  - gudhi=3.2.0=py38h45d8dc8_0
  - icu=64.2=he1b5a44_1
  - idna=2.9=py_1
  - importlib-metadata=1.6.0=py38h32f6830_0
  - importlib_metadata=1.6.0=0
  - ipykernel=5.2.1=py38h23f93f0_0
  - ipython=7.14.0=py38h32f6830_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.17.0=py38h32f6830_0
  - jinja2=2.11.2=pyh9f0ad1d_0
  - joblib=0.15.1=py_0
  - json5=0.9.0=py_0
  - jsonschema=3.2.0=py38h32f6830_1
  - jupyter_client=6.1.3=py_0
  - jupyter_core=4.6.3=py38h32f6830_1
  - jupyterlab=2.1.2=py_0
  - jupyterlab_server=1.1.4=py_0
  - kiwisolver=1.2.0=py38hbf85e49_0
  - krb5=1.17.1=h173b8e3_0
  - ld_impl_linux-64=2.34=h53a641e_0
  - libblas=3.8.0=16_openblas
  - libcblas=3.8.0=16_openblas
  - libcurl=7.69.1=h20c2e04_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-ng=9.2.0=h24d8f2e_2
  - libgfortran-ng=7.5.0=hdf63c60_6
  - liblapack=3.8.0=16_openblas
  - libopenblas=0.3.9=h5ec1e0e_0
  - libpng=1.6.37=hed695b0_1
  - libsodium=1.0.17=h516909a_0
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=9.2.0=hdf63c60_2
  - llvm-openmp=10.0.0=hc9558a2_0
  - markupsafe=1.1.1=py38h1e0a361_1
  - matplotlib-base=3.2.1=py38h2af1d28_0
  - mistune=0.8.4=py38h1e0a361_1001
  - mpfr=4.0.2=he80fd80_1
  - nbconvert=5.6.1=py38h32f6830_1
  - nbformat=5.0.6=py_0
  - ncurses=6.1=hf484d3e_1002
  - nose=1.3.7=py38h32f6830_1004
  - notebook=6.0.3=py38h32f6830_0
  - numpy=1.18.4=py38h8854b6b_0
  - openssl=1.1.1g=h516909a_0
  - packaging=20.1=py_0
  - pandas=1.0.3=py38hcb8c335_1
  - pandoc=2.9.2.1=0
  - pandocfilters=1.4.2=py_1
  - parso=0.7.0=pyh9f0ad1d_0
  - pcre=8.43=he6710b0_0
  - perl=5.26.2=h14c3975_0
  - pexpect=4.8.0=py38h32f6830_1
  - pickleshare=0.7.5=py38h32f6830_1001
  - pip=20.0.2=py38_3
  - prometheus_client=0.7.1=py_0
  - prompt-toolkit=3.0.5=py_0
  - ptyprocess=0.6.0=py_1001
  - pycparser=2.20=py_0
  - pygments=2.6.1=py_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyrsistent=0.16.0=py38h1e0a361_0
  - pysocks=1.7.1=py38h32f6830_1
  - python=3.8.2=he5300dc_7_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytz=2020.1=pyh9f0ad1d_0
  - pyzmq=19.0.1=py38ha71036d_0
  - readline=8.0=hf8c457e_0
  - requests=2.23.0=pyh8c360ce_2
  - scikit-learn=0.23.0=py38h3a94b23_0
  - scipy=1.4.1=py38h18bccfc_3
  - send2trash=1.5.0=py_0
  - setuptools=46.4.0=py38h32f6830_0
  - six=1.14.0=py_1
  - sqlite=3.30.1=hcee41ef_0
  - terminado=0.8.3=py38h32f6830_1
  - testpath=0.4.4=py_0
  - threadpoolctl=2.0.0=pyh5ca1d4c_0
  - tk=8.6.10=hed695b0_0
  - tornado=6.0.4=py38h1e0a361_1
  - tqdm=4.46.0=pyh9f0ad1d_0
  - traitlets=4.3.3=py38h32f6830_1
  - urllib3=1.25.9=py_0
  - wcwidth=0.1.9=pyh9f0ad1d_0
  - webencodings=0.5.1=py_1
  - wfdb=2.2.1=py_1
  - wheel=0.34.2=py_1
  - xz=5.2.5=h516909a_0
  - zeromq=4.3.2=he1b5a44_2
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h516909a_1006
prefix: /home/antic/anaconda3/envs/tda

